[tool.black]
line-length = 120
target-version = ['py312']
skip-string-normalization = true

[tool.flake8]
max-line-length = 120
exclude = ['migrations', 'static']

[tool.isort]
line_length = 120
skip = ['migrations', 'static']